config/routes.rb
Rails.application.routes.draw do
  root 'voitures#index'
  resources :voitures
  get 'voitures/index'
  get 'voitures/show'
  get 'voitures/new'
  get 'voitures/edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/voiture.rb
class Voiture < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/voitures_controller.rb
class VoituresController < ApplicationController
  def index
    @voitures = Voiture.all
  end

  def create
    voiture = Voiture.new(voiture_params)
    voiture.save
    redirect_to root_path
  end
  def show
    @voiture = Voiture.find(params[:id])
  end

  def new
  end

  def edit
    @voiture = Voiture.find(params[:id])
  end
  def update
    voiture = Voiture.find(params[:id])
    voiture.update(voiture_params)
    
    redirect_to root_path
  end

  def destroy
    voiture = Voiture.find(params[:id])
    voiture.destroy
    redirect_to root_path
  end

  private
  def voiture_params
      params.require(:voiture).permit(:num, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/voitures_helper.rb
module VoituresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoitureApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet"   href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/voitures/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 mb-4 display-4">Editer Voiture</h4>
  </div>
  <div class="row justify-content-center">
    <%= form_with(model: @voiture, local: true) do |form| %>
      <div class="form-group">
        <%= form.label :num %>
        <%= form.text_field :num, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.submit class: 'form-control btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/voitures/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 display-4">Liste Voitures</h4>
  </div>
  <%= link_to 'Ajouter une Voiture', new_voiture_path %>
  <% if @voitures.present? %>
    <div class="row justify-content-center">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col">Num</th>
            <th scope="col">Description</th>
            <th scope="col">Entrer</th>
            <th scope="col">Sortie</th>
            <th scope="col" colspan="3">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @voitures.each do |voiture| %>
            <tr>
              <td><%= voiture.num %></td>
              <td><%= voiture.description %></td>
              <td><%= voiture.created_at %></td>
              <td><%= voiture.updated_at %></td>
              <td><%= link_to 'Voire', voiture_path(voiture.id) %></td> 
              <td><%= link_to 'Editer', edit_voiture_path(voiture.id) %></td>
              <td><%= link_to 'Supprimer',
              voiture_path(voiture.id),
              method: :delete,
              data: { confirm: 'Vous ete sure?' } %>             
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <div class="p-3 mb-2 bg-light text-dark">
      <span class="text-info font-weight-bold">Bienvenue! </span>
      Crée votre  voiture
    </div>
  <% end %>
</div>

app/views/voitures/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 mb-4 display-4">Nouvelle Voiture</h4>
  </div>
  <div class="row justify-content-center">
    <%= form_with scope: :voiture, url: voitures_path, local: true do |form| %>
      <div class="form-group">
        <%= form.label :num %>
        <%= form.text_field :num, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.submit class: 'form-control btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/voitures/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 mb-4 display-4"> Details voiture <%= @voiture.id %></h4>
  </div>
  <div class="row justify-content-center">
    <table class="table">
      <tbody>
        <tr>
          <th>Num:</th>
          <td><%= @voiture.num %></td>
        </tr>
        <tr>
          <th>Description:</th>
          <td><%= @voiture.description %></td>
        </tr>
        <tr>
          <th>Entre:</th>
          <td><%= @voiture.created_at %></td>
        </tr>
        <tr>
          <th>Sortie:</th>
          <td><%= @voiture.updated_at %></td>
        </tr>
      </tbody>
    </table>
  </div>
  
</div>